from __future__ import annotations

import os
import re
import shutil
from collections import defaultdict
from pathlib import Path

from .config import FontSubsetConfig
from .font_io import content_hash, source_codepoints
from .models import FontFace
from .unicode_ranges import expand_ranges, ranges_to_css, to_ranges


def exposed_codepoints(faces: list[FontFace]) -> dict[str, set[int]]:
    min_codepoints: defaultdict[tuple[str, str], set[int]] = defaultdict(set)
    for face in faces:
        if face.tier == "min":
            min_codepoints[(face.family, face.script)].update(
                expand_ranges(face.ranges)
            )

    exposed: dict[str, set[int]] = {}
    for face in faces:
        coverage = expand_ranges(face.ranges)
        codepoints = (
            coverage
            if face.tier == "min"
            else coverage - min_codepoints[(face.family, face.script)]
        )
        if not codepoints:
            raise ValueError(f"{face.file_name} has an empty CSS unicode-range")
        exposed[face.file_name] = codepoints
    return exposed


def validate_outputs(
    config: FontSubsetConfig,
    faces: list[FontFace],
    staging_fonts: Path,
    generated_font_pattern: re.Pattern[str],
) -> None:
    referenced = {face.file_name for face in faces}
    generated = {
        path.name
        for path in staging_fonts.glob(f"*.{config.output_extension}")
        if generated_font_pattern.fullmatch(path.name)
    }
    if referenced != generated:
        raise ValueError("CSS references do not match generated WOFF2 files")

    exposed = exposed_codepoints(faces)
    family_codepoints: defaultdict[str, set[int]] = defaultdict(set)
    for face in faces:
        declared = exposed[face.file_name]
        overlap = family_codepoints[face.family] & declared
        if overlap:
            raise ValueError(
                f"{face.family} has overlapping unicode-range declarations"
            )
        family_codepoints[face.family].update(declared)

        output = staging_fonts / face.file_name
        if output.stat().st_size == 0:
            raise ValueError(f"Generated font is empty: {face.file_name}")
        actual = source_codepoints(output)
        coverage = expand_ranges(face.ranges)
        if coverage != actual:
            raise ValueError(
                f"{face.file_name} ranges do not match its cmap: "
                f"{len(coverage - actual)} missing, {len(actual - coverage)} extra"
            )
        if not declared <= actual:
            raise ValueError(f"{face.file_name} CSS range exceeds its cmap")

        match = generated_font_pattern.fullmatch(face.file_name)
        expected_hash = match.group("hash") if match else ""
        if expected_hash != content_hash(output, config.file_hash_length):
            raise ValueError(f"{face.file_name} content hash does not match its name")


def write_css_files(
    config: FontSubsetConfig,
    faces: list[FontFace],
    standard_hash: str,
    site_hash: str,
    site_output: Path,
    standard_output: Path,
) -> None:
    exposed = exposed_codepoints(faces)
    _write_css(
        config,
        [face for face in faces if face.tier == "min"],
        exposed,
        f"/* font-subset-site: {site_hash} */",
        site_output,
    )
    _write_css(
        config,
        [face for face in faces if face.tier != "min"],
        exposed,
        f"/* font-subset-standard: {standard_hash} */",
        standard_output,
    )


def _write_css(
    config: FontSubsetConfig,
    faces: list[FontFace],
    exposed: dict[str, set[int]],
    hash_comment: str,
    output: Path,
) -> None:
    header = (
        "/* Auto-generated by scripts/subsetFonts.py — DO NOT EDIT. */\n"
        f"{hash_comment}\n\n"
    )
    output.write_text(
        header
        + "\n\n".join(
            _font_face_rule(config, face, exposed[face.file_name]) for face in faces
        )
        + "\n",
        encoding="utf-8",
        newline="\n",
    )


def _font_face_rule(
    config: FontSubsetConfig,
    face: FontFace,
    codepoints: set[int],
) -> str:
    css = config.css
    return "\n".join(
        (
            "@font-face {",
            f"  font-family: '{face.family}';",
            f"  font-style: {css.font_style};",
            f"  font-weight: {css.font_weight};",
            f"  font-display: {css.font_display};",
            "  src:",
            f"    local('{css.local_fallback}'),",
            f"    url('{css.public_font_path}/{face.file_name}') "
            f"format('{config.output_format}');",
            f"  unicode-range: {ranges_to_css(to_ranges(codepoints))};",
            "}",
        )
    )


def commit_outputs(
    config: FontSubsetConfig,
    staging_root: Path,
    staged_site_css: Path,
    staged_standard_css: Path,
    managed_font_pattern: re.Pattern[str],
) -> None:
    fonts_dir = config.fonts_dir
    staged_fonts = staging_root / "fonts"
    fonts_backup = staging_root / "previous-fonts"
    fonts_were_present = fonts_dir.exists()
    css_outputs = (
        (
            staged_site_css,
            config.site_css_file,
            staging_root / "previous-fonts-subset.css",
        ),
        (
            staged_standard_css,
            config.standard_css_file,
            staging_root / "previous-fonts-standard.css",
        ),
    )
    for _, css_file, _ in css_outputs:
        css_file.parent.mkdir(parents=True, exist_ok=True)

    if fonts_were_present:
        for existing in fonts_dir.iterdir():
            if managed_font_pattern.fullmatch(existing.name):
                continue
            destination = staged_fonts / existing.name
            if existing.is_dir():
                shutil.copytree(existing, destination)
            else:
                shutil.copy2(existing, destination)

    fonts_backed_up = False
    fonts_installed = False
    css_backups: list[tuple[Path, Path]] = []
    css_installed: list[Path] = []
    try:
        if fonts_were_present:
            os.replace(fonts_dir, fonts_backup)
            fonts_backed_up = True
        for _, css_file, backup in css_outputs:
            if css_file.exists():
                os.replace(css_file, backup)
                css_backups.append((css_file, backup))
        os.replace(staged_fonts, fonts_dir)
        fonts_installed = True
        for staged_css, css_file, _ in css_outputs:
            os.replace(staged_css, css_file)
            css_installed.append(css_file)
    except Exception:
        for css_file in css_installed:
            css_file.unlink(missing_ok=True)
        if fonts_installed and fonts_dir.exists():
            shutil.rmtree(fonts_dir)
        if fonts_backed_up:
            os.replace(fonts_backup, fonts_dir)
        for css_file, backup in reversed(css_backups):
            os.replace(backup, css_file)
        raise
