export const CONFIG = {
  HOST: 'https://yuanshen.site',
  PATH: '/docs/',
  PATH_JA: '/docs/ja/',
  PATH_EN: '/docs/en/',
  LOGO: 'logo.jpg',
  REPO: 'https://gitee.com/KYJGYSDT/',
  REPO_DOCS: 'https://github.com/jiazengp/genshinmap-docs',
  COVER: 'https://yuanshen.site/tiles_test/4/ppp10_9.jpg',
  COVER_EN: 'https://yuanshen.site/tiles_test/4/ppp10_9.jpg',
  COVER_JA: 'https://yuanshen.site/tiles_test/4/ppp10_9.jpg',
  MASK_ICON: '20210609/safari-pinned-tab.svg',
  APP_TOUCH_ICON: 'https://yuanshen.site/v3/paimon_off@192.png',
  THEME_COLOR: '#ffffff',
  SITE_NAME: '原神地图',
  SITE_NAME_EN: 'Genshin Map',
  SITE_NAME_JA: '原神地図',
  DESCRIPTION: '米游社空荧酒馆制作的原神全资源攻略地图。',
  DESCRIPTION_EN:
    'The interactive map of Genshin full resources strategy made by Kongying Tavern.',
  DESCRIPTION_JA: '「米游社空荧酒馆」が作成した原神全資源攻略マップ',
  FAVICON: 'https://yuanshen.site/favicon.ico',
  RENDERER: 'webkit',
  TYPE: 'application',
  ANALYTICS_ID: 'G-Q2K9DXZCEY',
  AUTHOR: '(^_^)',
  RESTRICTIONS: '9+',
  TWITTER_ID: '',
  PUBID: 'ra-60c0af58a5d11388',
}
