import antfu from '@antfu/eslint-config'

const themeImportRestrictions = [
  { group: ['**/.vitepress/**'], message: 'src must not import from .vitepress by relative path; use src/forum/types.ts outlet' },
]

export default antfu({
  pnpm: true,
  unocss: true,
  typescript: true,
  vue: true,
  jsonc: true,
  yaml: true,
  // VitePress Markdown/MDC is checked by lint:md and lint:zh.
  markdown: false,
  formatters: {
    css: true,
  },
  ignores: [
    // Generated by vitepress-plugin-mdc-metadata during every build.
    '.vitepress/theme/mdc-components.mjs',
    '**/*.md',
    '**/dist',
    '**/node_modules',
    '**/public',
    '**/temp',
    '**/cache',
    // One-off refactor codemods kept as local history, not linted
    'scripts/refactor/**',
    // Regenerated by build:fonts from committed source TTFs.
    '.vitepress/theme/styles/fonts-standard.css',
    '.vitepress/theme/styles/fonts-subset.css',
  ],
  stylistic: {
    indent: 2,
    quotes: 'single',
    jsx: false,
  },

  overrides: {
    javascript: {
      // Keep one variable reporter for JS, TS and Vue; imports have their own rule.
      'no-unused-vars': 'off',
      'unused-imports/no-unused-vars': ['warn', {
        args: 'all',
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
        destructuredArrayIgnorePattern: '^_',
        ignoreRestSiblings: true,
      }],
      'no-console': 'warn',
      'default-param-last': 'error',
    },
    typescript: {
      'ts/no-explicit-any': 'warn',

      // 命名规范
      'ts/naming-convention': [
        'error',
        // TS interface 只允许大驼峰
        {
          selector: 'interface',
          format: ['PascalCase'],
          leadingUnderscore: 'forbid',
        },
        // TS Type 只允许大驼峰
        {
          selector: 'typeLike',
          format: ['PascalCase'],
          leadingUnderscore: 'forbid',
        },
        // 变量只允许大小驼峰、全大写下划线、全小写下划线
        {
          selector: 'variable',
          format: ['PascalCase', 'camelCase', 'UPPER_CASE', 'snake_case'],
          leadingUnderscore: 'allow',
          trailingUnderscore: 'allow',
        },
      ],

      'ts/no-unused-vars': 'off',
    },

    vue: {
      'vue/multi-word-component-names': 'off',

      'vue/prop-name-casing': ['error', 'camelCase'],

      'vue/no-ref-object-reactivity-loss': 'off',

      'vue/custom-event-name-casing': 'off',

      'vue/no-unused-vars': [
        'warn',
        {
          ignorePattern: '^_',
        },
      ],
    },
  },
}, {
  name: 'project/data-json',
  // Data generators own layout; still reject malformed JSON and duplicate keys.
  files: ['src/**/*.json', 'tests/**/fixtures/**/*.json'],
  rules: {
    'jsonc/array-bracket-spacing': 'off',
    'jsonc/comma-dangle': 'off',
    'jsonc/comma-style': 'off',
    'jsonc/indent': 'off',
    'jsonc/key-spacing': 'off',
    'jsonc/object-curly-newline': 'off',
    'jsonc/object-curly-spacing': 'off',
    'jsonc/object-property-newline': 'off',
    'jsonc/quote-props': 'off',
    'jsonc/quotes': 'off',
  },
}, {
  name: 'project/node-tests',
  files: ['tests/**/*.test.{ts,js,mjs,cjs}'],
  rules: {
    // The maintained logic suites use node:test, not Vitest.
    'test/no-import-node-test': 'off',
  },
}, {
  name: 'project/src-theme-boundary',
  files: ['src/**/*.{ts,tsx,mts,cts,js,jsx,mjs,cjs,vue}'],
  ignores: ['src/forum/types.ts', 'src/composables/usePostData.ts'],
  rules: {
    'no-restricted-imports': ['error', {
      patterns: themeImportRestrictions,
    }],
  },
}, {
  name: 'project/forum-layer-boundary',
  // Flat config replaces rule options, so retain both restrictions here.
  files: ['src/forum/{services,api}/**/*.{ts,tsx,mts,cts,js,jsx,mjs,cjs}'],
  rules: {
    'no-restricted-imports': ['error', {
      patterns: [
        ...themeImportRestrictions,
        { group: ['~/forum/components', '~/forum/components/**', '~/forum/composables', '~/forum/composables/**'], message: 'forum services/api must not import upward from components/composables' },
        { regex: '^\\.{1,2}/(?:\\.\\./)*(?:components|composables)(?:/|$)', message: 'forum services/api must not import upward from components/composables' },
      ],
    }],
  },
}).override('antfu/stylistic/rules', {
  // Universal stylistic rules also apply to JSON unless excluded explicitly.
  ignores: ['src/**/*.json', 'tests/**/fixtures/**/*.json'],
})
