packages: []

catalogs:
  build:
    '@lunariajs/core': ^0.1.1
    autoprefixer: ^10.4.21
    sass: ^1.93.2
    tsx: 4.19.2
    typescript: ^5.9.2
    unlazy: ^0.12.4
    unocss: ^66.5.2
    unocss-preset-animations: ^1.2.1
    unocss-preset-shadcn: ^0.5.0
    vite: ^7.1.7
    vitepress: 1.6.3
    vitepress-plugin-llms: ^1.7.5
  dev:
    '@actions/core': ^1.11.1
    '@antfu/eslint-config': ^5.4.1
    '@commitlint/cli': 19.6.1
    '@commitlint/config-conventional': 19.6.0
    '@commitlint/types': 19.5.0
    '@unlazy/vue': ^0.12.4
    '@unocss/eslint-config': ^66.5.2
    '@unocss/eslint-plugin': ^66.5.2
    '@unocss/extractor-mdc': 0.62.4
    '@unocss/preset-tagify': 0.64.1
    conventional-changelog-cli: 5.0.0
    cz-conventional-changelog: 3.3.0
    depcheck: ^1.4.7
    dotenv-cli: 8.0.0
    eslint: ^9.36.0
    fontaine: 0.5.0
    git-cz: 4.9.0
    husky: 9.1.7
    lint-staged: 15.3.0
    markdownlint-cli: 0.41.0
    open-editor: ^5.1.0
    sort-package-json: 2.12.0
    stylelint: 16.12.0
    stylelint-config-standard: 36.0.1
    stylelint-config-standard-scss: 13.1.0
    stylelint-order: 6.0.4
    taze: 0.16.9
    tsconfig-paths: 4.2.0
    vite-plugin-vue-devtools: 7.7.7
    zhlint: 0.8.2
  frontend:
    '@atlaskit/pragmatic-drag-and-drop': ^1.7.7
    '@atlaskit/pragmatic-drag-and-drop-hitbox': ^1.1.0
    '@fingerprintjs/fingerprintjs': 3.4.2
    '@floating-ui/dom': ^1.7.4
    '@iconify-json/ic': ^1.2.4
    '@iconify-json/logos': ^1.2.9
    '@iconify-json/lucide': ^1.2.68
    '@iconify-json/mdi': ^1.2.3
    '@iconify-json/ph': ^1.2.2
    '@number-flow/vue': ^0.4.8
    '@radix-icons/vue': ^1.0.0
    '@tanstack/vue-table': ^8.21.3
    '@vueuse/core': ^13.9.0
    '@vueuse/integrations': ^13.9.0
    '@vueuse/motion': ^3.0.3
    canvaskit-wasm: ^0.40.0
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    date-fns: ^4.1.0
    dayjs: ^1.11.18
    dexie: ^4.2.0
    embla-carousel-vue: ^8.6.0
    feed: ^5.1.0
    ky: ^1.10.0
    lodash-es: 4.17.21
    medium-zoom: ^1.1.0
    mitt: ^3.0.1
    motion-v: ^1.7.1
    path-to-regexp: ^8.3.0
    pinia: ^3.0.3
    qrcode: ^1.5.4
    radix-vue: ^1.9.17
    reka-ui: ^2.5.1
    sortablejs: ^1.15.6
    tailwind-merge: ^3.3.1
    thumbhash: ^0.1.1
    vaul-vue: ^0.4.1
    vue: ^3.5.22
    vue-request: ^2.0.4
    vue-sonner: ^2.0.8
    zod: ^4.1.11
  markdown:
    '@mdit/plugin-abbr': ^0.22.1
    '@mdit/plugin-container': ^0.22.1
    '@mdit/plugin-demo': ^0.22.2
    '@mdit/plugin-figure': ^0.22.1
    '@mdit/plugin-icon': ^0.22.1
    '@mdit/plugin-img-mark': ^0.22.1
    '@mdit/plugin-img-size': ^0.22.2
    '@mdit/plugin-mark': ^0.22.1
    '@mdit/plugin-ruby': ^0.22.1
    '@mdit/plugin-spoiler': ^0.22.1
    '@mdit/plugin-sub': ^0.22.1
    '@mdit/plugin-sup': ^0.22.1
    '@mdit/plugin-tasklist': ^0.22.1
    markdown-it: 14.1.0
    markdown-it-attrs: ^4.3.1
    markdown-it-container: 4.0.0
    markdown-it-footnote: ^4.0.0
    markdown-it-kbd-better: 1.2.5
  editor:
    '@tiptap/core': ^3.6.1
    '@tiptap/extension-character-count': ^3.6.1
    '@tiptap/extension-link': ^3.6.1
    '@tiptap/extension-mention': ^3.6.1
    '@tiptap/extension-placeholder': ^3.6.1
    '@tiptap/pm': ^3.6.1
    '@tiptap/starter-kit': ^3.6.1
    '@tiptap/static-renderer': ^3.6.1
    '@tiptap/suggestion': ^3.6.1
    '@tiptap/vue-3': ^3.6.1
    tiptap-markdown: ^0.9.0
  types:
    '@types/js-yaml': ^4.0.9
    '@types/lodash-es': 4.17.12
    '@types/markdown-it': 14.1.2
    '@types/markdown-it-attrs': ^4.1.3
    '@types/markdown-it-container': ^2.0.10
    '@types/markdown-it-footnote': 3.0.4
    '@types/node': 22.12.0
    '@types/sortablejs': ^1.15.8
  utils:
    js-yaml: ^4.1.0
    pnpm: 10.6.3
  conflicts_editor_h3_4_4:
    '@tiptap/core': ^3.6.1
    '@tiptap/extension-character-count': ^3.6.1
    '@tiptap/extension-mention': ^3.6.1
    '@tiptap/extension-placeholder': ^3.6.1
    '@tiptap/starter-kit': ^3.6.1
    '@tiptap/vue-3': ^3.6.1
  conflicts_frontend_h1_7_1:
    motion-v: ^1.7.1
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - vue-demi