catalog:
  '@actions/core': ^1.11.1
  '@antfu/eslint-config': ^4.12.0
  '@commitlint/cli': 19.6.1
  '@commitlint/config-conventional': 19.6.0
  '@commitlint/types': 19.5.0
  '@fingerprintjs/fingerprintjs': 3.4.2
  '@iconify-json/ic': ^1.2.2
  '@iconify-json/logos': ^1.2.4
  '@iconify-json/lucide': ^1.2.38
  '@iconify-json/mdi': ^1.2.3
  '@iconify-json/ph': ^1.2.2
  '@lunariajs/core': ^0.1.1
  '@mdit/plugin-container': ^0.16.0
  '@mdit/plugin-demo': ^0.18.0
  '@mdit/plugin-figure': ^0.16.0
  '@mdit/plugin-img-mark': ^0.16.0
  '@mdit/plugin-img-size': ^0.16.0
  '@mdit/plugin-mark': ^0.16.0
  '@mdit/plugin-spoiler': ^0.16.0
  '@mdit/plugin-sub': ^0.16.0
  '@mdit/plugin-sup': ^0.16.0
  '@radix-icons/vue': ^1.0.0
  '@tiptap/core': ^2.11.7
  '@tiptap/extension-character-count': ^2.11.7
  '@tiptap/extension-mention': ^2.11.7
  '@tiptap/starter-kit': ^2.11.7
  '@tiptap/vue-3': ^2.11.7
  '@types/js-yaml': ^4.0.9
  '@types/lodash-es': 4.17.12
  '@types/markdown-it': 14.1.2
  '@types/markdown-it-attrs': ^4.1.3
  '@types/markdown-it-container': ^2.0.10
  '@types/markdown-it-footnote': 3.0.4
  '@types/node': 22.10.2
  '@unlazy/vue': ^0.12.4
  '@unocss/eslint-config': ^66.1.0-beta.12
  '@unocss/eslint-plugin': ^66.1.0-beta.12
  '@unocss/extractor-mdc': 0.62.4
  '@unocss/preset-tagify': 0.64.1
  '@vueuse/core': ^13.1.0
  '@vueuse/integrations': ^13.1.0
  '@vueuse/motion': ^3.0.3
  autoprefixer: ^10.4.21
  canvaskit-wasm: ^0.40.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  conventional-changelog-cli: 5.0.0
  cz-conventional-changelog: 3.3.0
  dayjs: ^1.11.13
  depcheck: ^1.4.7
  dotenv-cli: 8.0.0
  embla-carousel-vue: ^8.6.0
  eslint: ^9.25.1
  feed: ^4.2.2
  fontaine: 0.5.0
  git-cz: 4.9.0
  husky: 9.1.7
  js-yaml: ^4.1.0
  ky: ^1.8.1
  lint-staged: 15.3.0
  lodash-es: 4.17.21
  markdown-it: 14.1.0
  markdown-it-attrs: ^4.3.1
  markdown-it-container: 4.0.0
  markdown-it-footnote: ^4.0.0
  markdown-it-kbd-better: 1.2.5
  markdownlint-cli: 0.41.0
  medium-zoom: ^1.1.0
  motion-v: ^0.13.1
  open-editor: ^5.1.0
  path-to-regexp: ^8.2.0
  pinia: ^3.0.2
  pnpm: 10.6.3
  qrcode: ^1.5.4
  radix-vue: ^1.9.17
  reka-ui: ^2.2.0
  sass: ^1.87.0
  sort-package-json: 2.12.0
  stylelint: 16.12.0
  stylelint-config-standard: 36.0.1
  stylelint-config-standard-scss: 13.1.0
  stylelint-order: 6.0.4
  tailwind-merge: ^3.2.0
  taze: 0.16.9
  thumbhash: ^0.1.1
  tsconfig-paths: 4.2.0
  tsx: 4.19.2
  typescript: ^5.8.3
  unlazy: ^0.12.4
  unocss: ^66.1.0-beta.12
  unocss-preset-animations: ^1.2.1
  unocss-preset-shadcn: ^0.5.0
  vaul-vue: ^0.4.1
  vite: ^6.3.2
  vite-plugin-inspect: 0.8.9
  vitepress: 1.6.3
  vitepress-plugin-llms: ^1.1.0
  vue: ^3.5.13
  vue-request: ^2.0.4
  vue-sonner: ^1.3.2
  zhlint: 0.8.2
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - vue-demi
