import { existsSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const IDENTIFIER_RE = /^[a-z_$][\w$]*$/i

/** Emit literal imports so Vite can bundle locale modules into its config. */
export function writeLocaleImporters(root: string): void {
  const localesDir = join(root, '.vitepress/locales')
  const locales = readdirSync(localesDir, { withFileTypes: true })
    .filter(entry => entry.isDirectory() && existsSync(join(localesDir, entry.name, 'index.ts')))
    .map(entry => entry.name)
    .sort()
  const lines = [
    '// Generated by pnpm init:locale. Keep literal imports for Vite config bundling.',
    'export const localeImporters: Record<string, Record<string, () => Promise<unknown>>> = {',
  ]
  for (const locale of locales) {
    const localeKey = IDENTIFIER_RE.test(locale) ? locale : `'${locale}'`
    lines.push(`  ${localeKey}: {`)
    const modules = readdirSync(join(localesDir, locale))
      .filter(file => file.endsWith('.ts'))
      .sort()
    for (const file of modules) {
      const name = file.slice(0, -3)
      const key = `'${name}'`
      lines.push(`    ${key}: () => import('../locales/${locale}/${file}'),`)
    }
    lines.push('  },')
  }
  lines.push('}', '')
  writeFileSync(join(root, '.vitepress/config/localeImporters.ts'), lines.join('\n'))
}
