// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CodeGroup: typeof import('./components/CodeGroup.ts')['default']
    CodeGroupItem: typeof import('./components/CodeGroupItem.vue')['default']
    LinkT: typeof import('./components/Link-t.vue')['default']
  }
}
