name: LUNARIA

on:
  # Trigger the workflow every time a pull request is opened or synchronized at the target `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  pull_request_target:
    types: [opened, synchronize]
    branches: [main]

# Allow this job to clone the repository and comment on the pull request
permissions:
  contents: read
  pull-requests: write

jobs:
  lunaria-overview:
    name: Generate Lunaria Overview
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Necessary for Lunaria to work properly
          # Makes the action clone the entire git history
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Generate Lunaria Overview
        uses: yanthomasdev/lunaria-action@v0.1.0
