name: SPELL_CHECK

on:
  pull_request:

permissions:
  contents: read

jobs:
  spell-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Check spelling
        uses: crate-ci/typos@v1.49.0
        with:
          config: ./.github/_typos.toml
